apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prod-app
  namespace: prod
spec:
  rules:
    - http:
        paths:
          - path: /mochi
            pathType: Prefix
            backend:
              service:
                name: mochi-svc-deployment
          - path: /puppy
            pathType: Prefix
            backend:
              service:
                name: puppy-svc-deployment
